### ISSUE TITLE
First shield study

### ISSUE THREAD

**Issue by groovecoder** [groovecoder/privacy-prefs#2]
Per https://github.com/mozilla/privacy-prefs/issues/1#issuecomment-248251699, set up shield study with these variations:
- device.sensors.enabled = false|true
  - Test Page: https://www.browserleaks.com/modernizr (Modernizr.devicemotion line)
- dom.battery.enabled = false|true
  - Test page: https://www.browserleaks.com/javascript

**Comment by fmarier** [comment]
I'm not sure about `beacon.enabled`. It's most likely to be used by advertisers, trackers and analytics (much like its predecessor `browser.send_pings`)  but if it's missing, it's likely that they'll just keep scripts running in the background or polling.

Therefore, it's an uncertain privacy win and a likely performance loss.

**Comment by fmarier** [comment]
I would suggest trying `media.peerconnection.ice.default_address_only = true` too. It's unlikely to be noticed by anybody given it only affects WebRTC on a local network.

**Comment by groovecoder** [comment]
Updated description to match. I'll get started.

**Comment by groovecoder** [comment]
@fmarier Hmm ... I've got the study add-on setting `media.peerconnection.ice.default_address_only = true`, but that doesn't seem to be enough to stop https://www.browserleaks.com/webrtc from seeing my local IP?

<img width="720" alt="webrtc-local-ip-default-address-only" src="https://cloud.githubusercontent.com/assets/71928/18722102/17fe115e-7ff9-11e6-9d88-19bf7e748912.png">

**Comment by fmarier** [comment]
Interesting, I'm also seeing this on Nightly 52.0a1 (2016-09-21) but not on Release/Beta 49.0 or on Aurora 50.0a2 (2016-09-19).

This appears to be a regression (likely in 51, but I haven't tested that version). I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1304600 for this.

Can we restrict the Shield test to Firefox 49/50 where we know it works?

**Comment by groovecoder** [comment]
@gregglind to limit a shield study to Firefox 49+50, is it better/possible to use:
`package.json`:

```
"engines": { "firefox": ">= 48.0 <= 50.0" }
```

or `study.js`:

```
let system = require('sdk/system')
...
isEligible () {
  if (system.version === `49.0` || system.version === `50.0`) {
    return true
  }
  return false
}
```

**Comment by gregglind** [comment]
I am actually ignorant on this point :)    I haven't explore the UX implications OR the technical aspects of this.
1.  It's really ONLY 49 or 50?  
2.  I expect the 'engines' key will do a subtler / better 'version compare', and may have a default response for when the install fails.  Try it?
3.  If you want to CONTROL the experience for ineligible users, I would do the later.  I would also suggest you see if versions START WITH `(49|50)\.` as a regex test.

**Comment by groovecoder** [comment]
@fmarier - based on https://wiki.mozilla.org/index.php?title=Media%2FWebRTC%2FPrivacy&diff=1148768&oldid=1128017 should I change this pref from `media.peerconnection.ice.default_address_only` to `media.peerconnection.ice.no_host` ?

**Comment by fmarier** [comment]
> should I change this pref from media.peerconnection.ice.default_address_only to media.peerconnection.ice.no_host

Yes, but only for Firefox >= 51+.

For Firefox < 51, it should still be the `default_address_only`.

So basically, it's not worth testing WebRTC stuff on Firefox < 51.
